### PR TITLE
Propose: Initiate Frontend Tech Radar

### PR DESCRIPTION
**Pull request by Ibwedagama**
### Adopt
- Javascript
- HTML 5
- CSS 3
- Vuex
- Tailwind CSS
- Vuetify
- ESLint
- Netlify

### Trial
- Prettier
- New Relic
- SonarQube

### Assess
- Typescript
- React
- Next Js
- Vue 3
- Nuxt 3
- Pinia

### Hold
- Vue 2
- Nuxt 2
- Jabar Design System UI Library

Open discussion @jabardigitalservice/jds-frontend

### CODE REVIEW

**Review by naufalihsank — APPROVED** [review]
so, there's no vue framework that we have high confidence to be used for now 🤣

**Comment by naufalihsank** [comment]
are the node packages (e.g. `vee-validate`, `vue-awesome-swiper`) should be included in these radar too ?

**Comment by azophy** [comment]
> so, there's no vue framework that we have high confidence to be used for now 🤣

There are still JQuery 🤣 

Jokes aside, I thinks this PR by bli @Ibwedagama already a great progress. At least we are now aware about our current stack issues, and could have better prioritize our resources to solve them. Good job sobat FE @jabardigitalservice/jds-frontend 👍

**Comment by azophy** [comment]
oh also, maybe we could include web bundling library here? (webpack/vite/etc) ?

**Comment by azophy** [comment]
other we could add here: FE performance measurement techniques & tools (web vitals, lighthouse, etc)

**Comment by Ibwedagama** [comment]
> so, there's no Vue framework that we have high confidence to be used for now 🤣

yes and if we're not prepared we'll face this same dilemma over and over again, should we stick to Vue 2 or Nuxt 2 (with our experience developing production-ready applications) or use the new industry standard Vue 3 and Nuxt 3 (with long time support from community) @naufalihsank 

IMHO we should not use Vue 2 or Nuxt 2 going forward, what do you think?

cc @jabardigitalservice/jds-frontend

**Comment by Ibwedagama** [comment]
> are the node packages (e.g. `vee-validate`, `vue-awesome-swiper`) should be included in these radar too ?

yes it should, we should add every package we've been using this far @naufalihsank 👍🏼

**Comment by Ibwedagama** [comment]
> > so, there's no vue framework that we have high confidence to be used for now 🤣
> 
> There are still JQuery 🤣
> 
> Jokes aside, I thinks this PR by bli @Ibwedagama already a great progress. At least we are now aware about our current stack issues, and could have better prioritize our resources to solve them. Good job sobat FE @jabardigitalservice/jds-frontend 👍

thank you @azophy there are a lot of tech stacks I'm not yet included in this initial propose. I hope we can add more stack going forward with help from our team @jabardigitalservice/jds-frontend

**Comment by Ibwedagama** [comment]
Also, I think we need to be more specific about package/library version, This is because some libraries introduce breaking changes on the newer version, and we have to choose carefully which version we should use in production.

@jabardigitalservice/jds-frontend

**Comment by naufalihsank** [comment]
> 



> > so, there's no Vue framework that we have high confidence to be used for now 🤣
> 
> yes and if we're not prepared we'll face this same dilemma over and over again, should we stick to Vue 2 or Nuxt 2 (with our experience developing production-ready applications) or use the new industry standard Vue 3 and Nuxt 3 (with long time support from community) @naufalihsank
> 
> IMHO we should not use Vue 2 or Nuxt 2 going forward, what do you think?
> 
> cc @jabardigitalservice/jds-frontend

agree, should we set priority for the assess category ? @Ibwedagama

**Comment by naufalihsank** [comment]
so how this repo iterate ?

are we @jabardigitalservice/jds-frontend members just create PR for updating this list ?

or should we initiate discuss first in separate thread/channel ?

**Comment by Ibwedagama** [comment]
> > 
> 
> > > so, there's no Vue framework that we have high confidence to be used for now 🤣
> > 
> > 
> > yes and if we're not prepared we'll face this same dilemma over and over again, should we stick to Vue 2 or Nuxt 2 (with our experience developing production-ready applications) or use the new industry standard Vue 3 and Nuxt 3 (with long time support from community) @naufalihsank
> > IMHO we should not use Vue 2 or Nuxt 2 going forward, what do you think?
> > cc @jabardigitalservice/jds-frontend
> 
> agree, should we set priority for the assess category ? @Ibwedagama

I think so, this Vue 3 and Nuxt 3 project started on DigiTeam @maruf12 @sheilaazhara will be our base of research for implementing this technology

**Comment by Ibwedagama** [comment]
> so how this repo iterate ?
> 
> are we @jabardigitalservice/jds-frontend members just create PR for updating this list ?
> 
> or should we initiate discuss first in separate thread/channel ?

after this PR merged, everyone should be allowed to make changes and discuss their opinion about what technology we should adopt, trial, asses, or drop

**Review by yoslie — APPROVED** [review]

**Review by azophy — APPROVED** [review]

**Review by doohanas — APPROVED** [review]

**Pull request merged**
